version: "3"
services: 
    task-tracker:
        image: node:14-alpine
        container_name: task-tracker
        logging: 
            driver: splunk
            options: 
                splunk-token: "jt7xay4s-aikl-nyoz-36gukwzmt1r2xlj1"
                splunk-url: "https://localhost:8088"
                splunk-insecureskipverify: "true"
                splunk-index: task-tracker
        working_dir: /usr/app
        command: /bin/sh -c "npm install && PORT=${TASK_TRACKER_PORT} npm run start"
        volumes: 
            - ./angular:/usr/app
            - angular:/usr/app/node_modules
        depends_on: 
            splunk:
                condition: service_healthy
    new-backend:
        image: node:14-alpine
        container_name: new-backend
        logging: 
            driver: splunk
            options: 
                splunk-token: "a5h7930q-vbw1-24de-eosu53mztzneuse3"
                splunk-url: "https://localhost:8088"
                splunk-insecureskipverify: "true"
                splunk-index: backend
        working_dir: /usr/app
        command: /bin/sh -c "npm install && PORT=${NEWER_BACKEND_PORT} npm run start"
        volumes: 
            - ./new_backend:/usr/app
            - new-backend:/usr/app/node_modules
        depends_on: 
            splunk:
                condition: service_healthy
            mongo:
                condition: service_started
    mongo:
        image: mongo
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: my_super_user
            MONGO_INITDB_ROOT_PASSWORD: my_super_password
            MONGO_INITDB_DATABASE: Example
        volumes: 
            - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    legacy-backend:
        image: node:14-alpine
        container_name: legacy-backend
        logging: 
            driver: splunk
            options: 
                splunk-token: "56z7m2f9-vbw1-24de-eosu53mztzneuse2"
                splunk-url: "https://localhost:8088"
                splunk-insecureskipverify: "true"
                splunk-index: backend
        working_dir: /usr/app
        command: /bin/sh -c "npm install && PORT=${BACKEND_PORT} npm run server"
        volumes: 
            - ./backend:/usr/app
            - legacy:/usr/app/node_modules
        depends_on: 
            splunk:
                condition: service_healthy
    backend-fallback:
        image: nginx
        container_name: backend-fallback
        logging: 
            driver: splunk
            options: 
                splunk-token: "c1513900-cb73-4b1a-a7bd-546bb26aefc4"
                splunk-url: "https://localhost:8088"
                splunk-insecureskipverify: "true"
                splunk-index: proxy
                tag: fallback
        ports:
            - 9000:5000
        depends_on: 
            legacy-backend:
                condition: service_started
            new-backend:
                condition: service_started
            splunk:
                condition: service_healthy
        volumes: 
            - ./backend-fallback/nginx.conf:/etc/nginx/nginx.conf
            - ./backend-fallback/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
            - logs-fallback:/var/log/nginx
    proxy:
        image: nginx
        container_name: proxy
        logging: 
            driver: splunk
            options: 
                splunk-token: "53b73db1-c549-4dd6-a718-04b630c0e30e"
                splunk-url: "https://localhost:8088"
                splunk-insecureskipverify: "true"
                splunk-index: proxy
                tag: proxy
        depends_on: 
            task-tracker:
                condition: service_started
            backend-fallback:
                condition: service_started
            splunk:
                condition: service_healthy
        ports: 
            - ${PROXY_PORT}:80
        volumes: 
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
            - logs-proxy:/var/log/nginx
    splunk:
        image: splunk/splunk
        container_name: splunk
        environment: 
            - SPLUNK_PASSWORD=Test1234
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_ROOT_ENDPOINT=/splunk
            - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/3258/release/3.0.0/download
            - SPLUNKBASE_USERNAME=${SPLUNKBASE_USERNAME}
            - SPLUNKBASE_PASSWORD=${SPLUNKBASE_PASSWORD}
            - SPLUNK_NGINX_TOKEN=${SPLUNK_NGINX_TOKEN}
            - SPLUNK_BACKEND_FALLBACK_TOKEN=${SPLUNK_BACKEND_FALLBACK_TOKEN}
        volumes:
            - ./splunk/httpinput/local:/opt/splunk/etc/apps/splunk_httpinput/local
            - ./splunk/Splunk_TA_nginx/local:/opt/splunk/etc/apps/Splunk_TA_nginx/local
            - ./splunk/search/local:/opt/splunk/etc/apps/search/local
            - logs-proxy:/mnt/logs/proxy
            - logs-fallback:/mnt/logs/fallback
        ports: 
            - 8088:8088
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 10
volumes: 
    angular:
    legacy:
    new-backend:
    logs-proxy:
    logs-fallback: